### ISSUE TITLE
data quality check

### ISSUE THREAD

**Issue by MarioGarbelli** [ec-jrc/COVID-19#1]
- From 2020-03-26: CumulativePositive is always 0 at region level in France (except for NOT SPECIFIED region). Conseguently, CurrentlyPositive is negative.

- Before 2020-03-26: CumulativeDeceased, CumulativeRecovered and IntensiveCare are always 0 at region level in France (except for NOT SPECIFIED region)

- The following regions haven't latitude and longitude: West North (FIN), Estrageiro (PRT), Argeș (ROU), Bacău (ROU), Botoșani (ROU), Brașov (ROU), Brăila (ROU), București (ROU), Buzău (ROU), Călărași (ROU), Caraș-Severin (ROU), Costanza (ROU), Dâmbovița (ROU), Galați (ROU), Iași (ROU), Ialomița (ROU), Mehedinți (ROU), Mureș (ROU), Neamț (ROU), Sălaj (ROU), Timiș (ROU), Vâlcea (ROU), Altai Republic (RUS), Chukotka (RUS), Nenets (RUS), England (GBR)

**Comment by JumbaJookiba** [comment]
Dear sir,


  *   France said they are not able to provide data at regional level: the fictitious region NOT SPECIFIED carries the data at national level. It happens also for other countries. I think that the negative data should be replaced by 0
  *   See above
  *   Some of those regions are fictitious as well, like Estrageiro, that reports the number of foreign people in the country affected by the Covid disease. For the Others, we perform regular consistency checks, that will fix it; but Thanks for noticing.

Daniele A. GALLIANO
Ingegnere

Da: MarioGarbelli<mailto:notifications@github.com>
Inviato: martedì 5 maggio 2020 10:35
A: ec-jrc/COVID-19<mailto:COVID-19@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [ec-jrc/COVID-19] data quality check (#1)


  *   From 2020-03-26: CumulativePositive is always 0 at region level in France (except for NOT SPECIFIED region). Conseguently, CurrentlyPositive is negative.
  *   Before 2020-03-26: CumulativeDeceased, CumulativeRecovered and IntensiveCare are always 0 at region level in France (except for NOT SPECIFIED region)
  *   The following regions haven't latitude and longitude: West North (FIN), Estrageiro (PRT), Argeș (ROU), Bacău (ROU), Botoșani (ROU), Brașov (ROU), Brăila (ROU), București (ROU), Buzău (ROU), Călărași (ROU), Caraș-Severin (ROU), Costanza (ROU), Dâmbovița (ROU), Galați (ROU), Iași (ROU), Ialomița (ROU), Mehedinți (ROU), Mureș (ROU), Neamț (ROU), Sălaj (ROU), Timiș (ROU), Vâlcea (ROU), Altai Republic (RUS), Chukotka (RUS), Nenets (RUS), England (GBR)
