### ISSUE TITLE
Searching for the raw data used to build the Dashboard measures

### ISSUE THREAD

**Issue by Abdelkrim** [ec-jrc/COVID-19#12]
# the question

to whom it may concern,
where can I find the raw data used to build the page displaying the measures applied in each EU MS [1].

I would like to build a mobile app that displays the information for everyone

[1] https://covid-statistics.jrc.ec.europa.eu/Measure/DashboardMeasures?view=1

Kind regards,
Abdelkrim

## screenshot

![jrc-dashboard-measure-covid](https://user-images.githubusercontent.com/791663/82905028-99d9fc00-9f63-11ea-9251-6879ebc43324.png)

**Comment by IndefiniteBen** [comment]
You can download historical data with a link of the format: 
`https://covid-statistics.jrc.ec.europa.eu/api/Measure/GetHistory/<ISO3 code>/true` 
The latest update can be downloaded with a link of the format:
 `https://covid-statistics.jrc.ec.europa.eu/api/Measure/GetLast/<ISO3 code>`

**Comment by Abdelkrim** [comment]
thank you @IndefiniteBen

**Comment by IndefiniteBen** [comment]
You can also download similar data for the entire world from https://www.acaps.org/covid19-government-measures-dataset as mentioned in #5 and #6.

**Comment by Abdelkrim** [comment]
@IndefiniteBen thank you
