### ISSUE TITLE
Bulgaria 2021-06-21 records

### ISSUE THREAD

**Issue by jeffpires** [ec-jrc/COVID-19#16]
A set of BGR records dated 2021-06-21 was was introduced this morning.

**Comment by jeffpires** [comment]
The BGR 2021-06-21 records were corrected yesterday, but this morning a new set of BGR records dated 2021-06-22 have been introduced.

**Comment by JumbaJookiba** [comment]
This issue comes from the source of the data.
We applied a workaround and informed the authoritative office in charge of the data source, which replied they are working on it.
