### ISSUE TITLE
Difference between 'all-days' and other files for CumulativePositive

### ISSUE THREAD

**Issue by resurepus** [ec-jrc/COVID-19#22]
For Iceland, from July 2nd CumulativePositive is higher in the 'single date' and 'latest' file than in the 'all-days' file.

all-days: 2020-08-26,ISL,Iceland,64.963942,-19.021169,**2077**,10,,2067,,,False,True,IS
single: 2020-08-26,ISL,Iceland,64.963942,-19.021169,**3891**,10,,,,,False,True,IS
latest: 2020-08-26,ISL,Iceland,64.963942,-19.021169,**3891**,10,,,,,False,True,IS

For Slovenia, there is a similar pattern

all-days: 2020-08-25,SVN,Slovenia,46.145528,14.974541,**2722**,133,376,2213,20,0,True,True,SI
single: 2020-08-25,SVN,Slovenia,46.145528,14.974541,**3933**,133,376,3424,20,0,True,True,SI
latest: 2020-08-25,SVN,Slovenia,46.145528,14.974541,**3933**,133,376,3424,20,0,True,True,SI

**Comment by JumbaJookiba** [comment]
Fixed both.
