### ISSUE TITLE
Containment Measures

### ISSUE THREAD

**Issue by MP1285** [ec-jrc/COVID-19#5]
Hello - is there a repository/database within this folder for national containment measures, as documented in this dashbord (https://covid-statistics.jrc.ec.europa.eu/Measure/DashboardMeasures) and readme. It would be great to have a time series with updates for each country. Thanks

**Comment by JumbaJookiba** [comment]
I am sorry, but the measure database is provided only for online consultation, but no history will be shared.

**Comment by jeffpires** [comment]
@MP1285 check this ACAPS resource, it may have what you are looking for:
https://www.acaps.org/covid19-government-measures-dataset

**Comment by MP1285** [comment]
Thank you !
