### ISSUE TITLE
Add country measures data

### ISSUE THREAD

**Issue by alsino** [ec-jrc/COVID-19#6]
Hi there,

thanks for providing this data. It is very useful. I am wondering whether you could also provide the data on **country measures against COVID-19** as included in the following table in machine readable format:
https://covid-statistics.jrc.ec.europa.eu/Measure/DashboardMeasures#

So far, I have not been able to find this data in anywhere. Thanks!

**Comment by szeemi** [comment]
Same request here!

best

**Comment by JumbaJookiba** [comment]
As suggested in https://github.com/ec-jrc/COVID-19/issues/5#issuecomment-626760168
I think you should get from ACAPS the data you are looking for.
