### ISSUE TITLE
Hungary Region name encoding change

### ISSUE THREAD

**Issue by jeffpires** [ec-jrc/COVID-19#7]
In today's updated regional data for Hungary, 13 May, region names are encoded differently from the way they have been represented before, resulting in mismatched updates and duplicate records.

2020-05-12 | HUN | Hungary | Bács-Kiskun | 46.563665 | 19.374746 | 23 | 0 | 0 | 23 | 0 | 0 | True | True
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | 2020-05-13 | HUN | Hungary | Baranya | 46.043048 | 18.197022 | 36 | 0 | 0 | 36 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | B�cs-Kiskun |   |   | 23 | 0 | 0 | 23 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Békés | 46.735413 | 21.006326 | 16 | 0 | 0 | 16 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | B�k�s |   |   | 11 | 0 | 0 | 11 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Borsod-Aba�j-Zempl�n |   |   | 64 | 0 | 0 | 64 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Borsod-Abaúj-Zemplén | 48.200164 | 20.962472 | 64 | 0 | 0 | 64 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Budapest | 47.486226 | 19.102958 | 1609 | 0 | 0 | 1609 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Csongrád | 46.429441 | 20.23317 | 108 | 0 | 0 | 108 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Csongr�d |   |   | 113 | 0 | 0 | 113 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Fejér | 47.130985 | 18.532031 | 338 | 0 | 0 | 338 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Fej�r |   |   | 338 | 0 | 0 | 338 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Gy?r-Moson-Sopron |   |   | 83 | 0 | 0 | 83 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Győr-Moson-Sopron | 47.642476 | 17.280184 | 83 | 0 | 0 | 83 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Hajd�-Bihar |   |   | 23 | 0 | 0 | 23 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Hajdú-Bihar | 47.472629 | 21.459389 | 23 | 0 | 0 | 23 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Heves | 47.856454 | 20.175008 | 17 | 0 | 0 | 17 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Hungary | 47.164638 | 19.508944 | 0 | 0 | 0 | 0 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Jász-Nagykun-Szolnok | 47.112794 | 20.341909 | 23 | 0 | 0 | 23 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | J�sz-Nagykun-Szolnok |   |   | 23 | 0 | 0 | 23 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Komárom-Esztergom | 47.610748 | 18.309797 | 174 | 0 | 0 | 174 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Kom�rom-Esztergom |   |   | 176 | 0 | 0 | 176 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | N�gr�d |   |   | 25 | 0 | 0 | 25 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Nógrád | 47.988372 | 19.52022 | 25 | 0 | 0 | 25 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | NOT SPECIFIED |   |   | 0 | 430 | 950 | -1380 | 688 | 45 | True | True
  | 2020-05-13 | HUN | Hungary | Pest | 47.252834 | 19.743062 | 456 | 0 | 0 | 456 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Somogy | 46.452574 | 17.603217 | 28 | 0 | 0 | 28 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Szabolcs-Szatmár-Bereg | 47.998398 | 22.083465 | 47 | 0 | 0 | 47 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Szabolcs-Szatm�r-Bereg |   |   | 47 | 0 | 0 | 47 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Tolna | 46.512422 | 18.535403 | 17 | 0 | 0 | 17 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Vas | 47.147868 | 16.751348 | 14 | 0 | 0 | 14 | 0 | 0 | True | True
  | 2020-05-12 | HUN | Hungary | Veszprém | 47.131402 | 17.65231 | 62 | 0 | 0 | 62 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Veszpr�m |   |   | 62 | 0 | 0 | 62 | 0 | 0 | True | True
  | 2020-05-13 | HUN | Hungary | Zala | 46.692149 | 16.903237 | 176 | 0 | 0

**Comment by JumbaJookiba** [comment]
Dear Jeff,

Thanks for your help.
We are testing an additional ingestion method.
The DB will be cleaned up asap.

Best regards,

Daniele A. GALLIANO
Ingegnere

Da: Jeff<mailto:notifications@github.com>
Inviato: mercoledì 13 maggio 2020 14:24
A: ec-jrc/COVID-19<mailto:COVID-19@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [ec-jrc/COVID-19] Hungary Region name encoding change (#7)


In today's updated regional data for Hungary, 13 May, region names are encoded differently from the way they have been represented before, resulting in mismatched updates and duplicate records.
2020-05-12
HUN
Hungary
Bács-Kiskun
46.563665
19.374746
23
0
0
23
0
0
True
True

2020-05-13
HUN
Hungary
Baranya
46.043048
18.197022
36
0
0
36
0
0
True

2020-05-13
HUN
Hungary
B�cs-Kiskun


23
0
0
23
0
0
True

2020-05-12
HUN
Hungary
Békés
46.735413
21.006326
16
0
0
16
0
0
True

2020-05-13
HUN
Hungary
B�k�s


11
0
0
11
0
0
True

2020-05-13
HUN
Hungary
Borsod-Aba�j-Zempl�n


64
0
0
64
0
0
True

2020-05-12
HUN
Hungary
Borsod-Abaúj-Zemplén
48.200164
20.962472
64
0
0
64
0
0
True

2020-05-13
HUN
Hungary
Budapest
47.486226
19.102958
1609
0
0
1609
0
0
True

2020-05-12
HUN
Hungary
Csongrád
46.429441
20.23317
108
0
0
108
0
0
True

2020-05-13
HUN
Hungary
Csongr�d


113
0
0
113
0
0
True

2020-05-12
HUN
Hungary
Fejér
47.130985
18.532031
338
0
0
338
0
0
True

2020-05-13
HUN
Hungary
Fej�r


338
0
0
338
0
0
True

2020-05-13
HUN
Hungary
Gy?r-Moson-Sopron


83
0
0
83
0
0
True

2020-05-12
HUN
Hungary
Győr-Moson-Sopron
47.642476
17.280184
83
0
0
83
0
0
True

2020-05-13
HUN
Hungary
Hajd�-Bihar


23
0
0
23
0
0
True

2020-05-12
HUN
Hungary
Hajdú-Bihar
47.472629
21.459389
23
0
0
23
0
0
True

2020-05-13
HUN
Hungary
Heves
47.856454
20.175008
17
0
0
17
0
0
True

2020-05-13
HUN
Hungary
Hungary
47.164638
19.508944
0
0
0
0
0
0
True

2020-05-12
HUN
Hungary
Jász-Nagykun-Szolnok
47.112794
20.341909
23
0
0
23
0
0
True

2020-05-13
HUN
Hungary
J�sz-Nagykun-Szolnok


23
0
0
23
0
0
True

2020-05-12
HUN
Hungary
Komárom-Esztergom
47.610748
18.309797
174
0
0
174
0
0
True

2020-05-13
HUN
Hungary
Kom�rom-Esztergom


176
0
0
176
0
0
True

2020-05-13
HUN
Hungary
N�gr�d


25
0
0
25
0
0
True

2020-05-12
HUN
Hungary
Nógrád
47.988372
19.52022
25
0
0
25
0
0
True

2020-05-13
HUN
Hungary
NOT SPECIFIED


0
430
950
-1380
688
45
True

2020-05-13
HUN
Hungary
Pest
47.252834
19.743062
456
0
0
456
0
0
True

2020-05-13
HUN
Hungary
Somogy
46.452574
17.603217
28
0
0
28
0
0
True

2020-05-12
HUN
Hungary
Szabolcs-Szatmár-Bereg
47.998398
22.083465
47
0
0
47
0
0
True

2020-05-13
HUN
Hungary
Szabolcs-Szatm�r-Bereg


47
0
0
47
0
0
True

2020-05-13
HUN
Hungary
Tolna
46.512422
18.535403
17
0
0
17
0
0
True

2020-05-13
HUN
Hungary
Vas
47.147868
16.751348
14
0
0
14
0
0
True

2020-05-12
HUN
Hungary
Veszprém
47.131402
17.65231
62
0
0
62
0
0
True

2020-05-13
HUN
Hungary
Veszpr�m


62
0
0
62
0
0
True

2020-05-13
HUN
Hungary
Zala
46.692149
16.903237
176
0
0

**Comment by JumbaJookiba** [comment]
Data are now corrected.
Next report generation (every 30') will reflect this
